# Russian translation for PyVSB
#
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: Konishchev Dmitry <konishchev@gmail.com>\n"
"Last-Translator: Konishchev Dmitry <konishchev@gmail.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: backup.py:82
msgid "Creating tar archive for current backup failed."
msgstr "Создание tar архива для текущего бэкапа завершилось неудачей."

#: backup.py:86
#, python-format
msgid "Backup started with configuration file '%s' at %s."
msgstr "Бэкап с конфигурационным файлом '%s' начат в %s."

#: backup.py:95
#, python-format
msgid "Backup completed with errors at %s."
msgstr "Бэкап завершен с ошибками в %s."

#: backup.py:97
#, python-format
msgid "Backup completed with warnings at %s."
msgstr "Бэкап завершился с некритическими ошибками в %s."

#: backup.py:99
#, python-format
msgid "Backup successfully completed at %s."
msgstr "Бэкап успешно завершен в %s."

#: backup.py:119
#, python-format
msgid "Maximum recursion depth exceeded while backing up file '%s'."
msgstr ""
"Достигнуто максимальное количество рекурсивных вызовов функций при бэкапе "
"файла '%s'."

#: backup.py:126
#, python-format
msgid "Skipping '%s' - it is already treated."
msgstr "Пропускаем '%s' - он уже был обработан."

#: backup.py:136
#, python-format
msgid "'%s' is matches filter '%s'."
msgstr "'%s' подходит под фильтр '%s'."

#: backup.py:139
#, python-format
msgid "Skipping '%s' - it has been filtered."
msgstr "Пропускаем '%s' - он был отфильтрован."

#: backup.py:146
#, python-format
msgid "Skipping '%s' - it has been filtered by default filter."
msgstr "Пропускаем '%s' - он был отфильтрован фильтром по умолчанию."

#: backup.py:151 backup.py:396
#, python-format
msgid "Backing up '%s'..."
msgstr "Бэкапим '%s'..."

#: backup.py:213 lib.py:386
#, python-format
msgid "Can't read directory '%s': %s."
msgstr "Ошибка при чтении директории '%s': %s."

#: backup.py:229
#, python-format
msgid "Backing up of '%s' failed."
msgstr "Бэкап '%s' завершился неудачей."

#: backup.py:244
msgid ""
"No files added to backup archive. Backup is empty. Not adding it to the "
"current group."
msgstr ""
"Ни одного файла не было добавлено в архив бэкапа. Бэкап пуст. Не добавляем "
"его в текущую группу."

#: backup.py:248
msgid "Creating backup data archive failed."
msgstr "Создание архива с данными бэкапа завершилось неудачей."

#: backup.py:258
msgid "Not all backup files has been written. Backup is not full."
msgstr "Были записаны не все файлы бэкапа. Бэкап будет не полным."

#: backup.py:260
msgid "All backup files has been written."
msgstr "Все файлы бэкапа были успешно записаны."

#: backup.py:284
msgid "Maximum recursion depth exceeded while creating empty directory tree."
msgstr ""
"Максимальное количество рекурсивных вызовов функций было достигнуто при "
"создании пустого дерева каталогов."

#: backup.py:310
#, python-format
msgid ""
"Error while creating empty directory tree: '%s' is not directory or link to "
"directory."
msgstr ""
"Ошибка при создании пустого дерева каталогов: '%s' - не директория и не "
"ссылка на директорию."

#: backup.py:324
#, python-format
msgid ""
"'%s' was a directory, but now it is link to '%s'. Rejecting link creation."
msgstr ""
"'%s' была директорией, но сейчас это ссылка на '%s'. Пропускаем создание "
"ссылки."

#: backup.py:327
#, python-format
msgid ""
"'%s' was link to '%s', but now it is a directory. Rejecting directory "
"creation."
msgstr ""
"'%s' была ссылкой на '%s', но сейчас это директория. Пропускаем создание "
"директории."

#: backup.py:337
#, python-format
msgid ""
"'%s' was link to '%s', but now it is link to '%s'. Rejecting link changing."
msgstr ""
"'%s' была ссылкой на '%s', но сейчас это ссылка на '%s'. Пропускаем "
"изменение ссылки."

#: backup.py:340 config.py:84 config.py:201 config.py:272 main.py:107
#: storage.py:50 storage.py:254 storage.py:259 storage.py:323 storage.py:327
#: storage.py:457
msgid "Logical error!"
msgstr "Логическая ошибка!"

#: backup.py:351
#, python-format
msgid "Cycle paths detected at '%s' while creating empty directory tree."
msgstr ""
"При создании пустого дерева каталогов были обнаружены закольцованные пути "
"при обработке пути '%s'."

#: backup.py:369
#, python-format
msgid "'%s' is not a directory or a link to directory."
msgstr "'%s' - не директория и не ссылка на директорию."

#: backup.py:386
#, python-format
msgid "Running backup entry '%s' start_before command '%s'..."
msgstr "Запускаем для элемента бэкапа '%s' start_before команду '%s'..."

#: backup.py:391
#, python-format
msgid ""
"Backup entry '%s' start_before command return exit status %d. Shell output:\n"
"%s"
msgstr ""
"start_before команда элемента бэкапа '%s' возвратила статус завершения %d. "
"Вывод командной оболочки:\n"
"%s"

#: backup.py:402
#, python-format
msgid "Creating empty directory tree for backup entry '%s' failed."
msgstr ""
"Создание пустого дерева каталогов для элемента бэкапа '%s' завершилось "
"неудачей."

#: backup.py:403 backup.py:407
#, python-format
msgid "Backup of backup entry '%s' failed."
msgstr "Бэкап элемента бэкапа '%s' завершился неудачей."

#: backup.py:411
#, python-format
msgid "Running backup entry '%s' start_after command '%s'..."
msgstr "Запускаем для элемента бэкапа '%s' start_after команду '%s'..."

#: backup.py:416
#, python-format
msgid ""
"Backup entry '%s' start_after command return exit status %d. Shell output:\n"
"%s"
msgstr ""
"start_after команда элемента бэкапа '%s' возвратила статус завершения %d. "
"Вывод командной оболочки:\n"
"%s"

#: backup.py:435
#, python-format
msgid "Can't read file '%s': %s."
msgstr "Ошибка при чтении файла '%s': %s."

#: backup.py:450
#, python-format
msgid "Can't open temp file '%s' for writing: %s."
msgstr "Не удалось открыть временный файл '%s' на запись: %s."

#: backup.py:461
#, python-format
msgid "File type of '%s' has been changed."
msgstr "Тип файла '%s' изменился."

#: backup.py:478
#, python-format
msgid "Error while copying file '%s' to '%s': %s."
msgstr "Ошибка при копировании файла '%s' в '%s': '%s'."

#: backup.py:485
msgid "Getting temp storage file info failed."
msgstr "Получение информации о временном файле архива завершилось неудачей."

#: backup.py:513
msgid "Sending email report..."
msgstr "Отправляем email отчет..."

#: backup_fs.py:82
#, python-format
msgid "Getting unique files list for backup '%s' in group '%s'..."
msgstr "Получаем список уникальных файлов для бэкапа '%s' в группе '%s'..."

#: backup_fs.py:98
#, python-format
msgid "Bad unique files list line in '%s': '%s'."
msgstr "Неверная строка в списке уникальных файлов '%s': '%s'."

#: backup_fs.py:103
#, python-format
msgid ""
"Unique files list '%s' is broken! It is not ending by empty line. Skiping "
"it's last line."
msgstr ""
"Список уникальных файлов '%s' поврежден! Он не заканчивается пустой строкой. "
"Пропускаем последнюю его строку."

#: backup_fs.py:105
#, python-format
msgid "Can't read unique files list '%s': %s."
msgstr "Ошибка при чтении списка уникальных файлов '%s': %s."

#: backup_fs.py:117
#, python-format
msgid "Bad backup '%s': it is not exists."
msgstr "Неверный бэкап '%s': такого файла или директории не существует."

#: backup_fs.py:121
#, python-format
msgid "Bad backup '%s': it is not a directory."
msgstr "Неверный бэкап '%s': это не директория."

#: backup_fs.py:128
#, python-format
msgid "'%s' is not a backup root."
msgstr "'%s' - не корневая директория бэкапа."

#: backup_fs.py:135
#, python-format
msgid "Bad backup root: '%s' is not a directory."
msgstr "Неверная корневая директория бэкапа: '%s' - не директория."

#: backup_fs.py:139
msgid "Backup root directory is not exists. Creating it..."
msgstr "Корневая директория бэкапа не существует. Создаем ее..."

#: backup_fs.py:142
msgid "Creating backup root directory failed."
msgstr "Создание корневой директории бэкапа завершилось неудачей."

#: backup_fs.py:145
#, python-format
msgid "Backup root directory '%s' is not exists."
msgstr "Корневой каталог бэкапа '%s' не существует."

#: backup_fs.py:148
#, python-format
msgid "Bad backup root directory '%s'."
msgstr "Неверный корневой каталог бэкапа '%s'."

#: backup_fs.py:183
msgid "Finalizing current backup failed."
msgstr "Запись файлов текущего бэкапа завершилась неудачей."

#: backup_fs.py:211
msgid "Creating current backup directory failed."
msgstr "Создание директории для текущего бэкапа завершилось неудачей."

#: backup_fs.py:228
#, python-format
msgid "Bad backup temp directory: '%s' is not a directory."
msgstr "Неверная временная директория бэкапа: '%s' - не директория."

#: backup_fs.py:234
#, python-format
msgid "Creating backup temp directory '%s' failed."
msgstr "Создание временной директории бэкапа '%s' завершилось неудачей."

#: backup_fs.py:248
msgid "Current group is broken! Removing it..."
msgstr "Текущая группа повреждена! Удаляем ее..."

#: backup_fs.py:260
#, python-format
msgid "Finalizing current group to '%s'..."
msgstr "Завершаем формирование текущей группы, перемещая ее в '%s'..."

#: backup_fs.py:262
msgid "Finalizing current group failed."
msgstr "Не удалось завершить формирование текущей группы."

#: backup_fs.py:286
#, python-format
msgid "Bad extern files list line in '%s': '%s'."
msgstr "Неверная строка в списке внешних файлов '%s': '%s'."

#: backup_fs.py:291
#, python-format
msgid ""
"Extern files list '%s' is broken! It is not ending by empty line. Skiping "
"it's last line."
msgstr ""
"Список внешних файлов '%s' поврежден! Он не заканчивается пустой строкой. "
"Пропускаем последнюю его строку."

#: backup_fs.py:293
#, python-format
msgid "Can't read extern files list '%s': %s."
msgstr "Ошибка при чтении списка внешних файлов '%s': %s."

#: backup_fs.py:320
#, python-format
msgid "Can't read group '%s' directory '%s': %s."
msgstr "Ошибка при чтении директории группы '%s' ('%s'): %s."

#: backup_fs.py:321
#, python-format
msgid "Getting group '%s' backups list failed."
msgstr "Получение списка бэкапов группы '%s' завершилось неудачей."

#: backup_fs.py:333
#, python-format
msgid "Bad backup '%s' in group '%s'."
msgstr "Неверный бэкап '%s' в группе '%s'."

#: backup_fs.py:350
#, python-format
msgid "Getting group '%s' unique files list failed."
msgstr "Получение списка уникальных файлов группы '%s' завершилось неудачей."

#: backup_fs.py:372
msgid "Trying to lock backup root..."
msgstr "Пытаемся заблокировать корневую директорию бэкапа..."

#: backup_fs.py:382
#, python-format
msgid "Can't lock backup root '%s': can't create (open) lock file '%s' (%s)."
msgstr ""
"Не удалось заблокировать корневую директорию бэкапа '%s': не удалось создать "
"(открыть) файл блокировки '%s' (%s)."

#: backup_fs.py:397
#, python-format
msgid "Can't lock file '%s': %s."
msgstr "Не удалось заблокировать файл '%s': %s."

#: backup_fs.py:429
#, python-format
msgid ""
"Can't lock backup root '%s': backing up or restoring is already started by "
"another process."
msgstr ""
"Не удалось заблокировать корневую директорию бэкапа '%s': бэкап или "
"восстановление уже запущены другим процессом."

#: backup_fs.py:437
msgid "Backup root locked."
msgstr "Корневая директория бэкапа заблокирована."

#: backup_fs.py:463
#, python-format
msgid "Removing backup temp directory '%s' failed."
msgstr "Удаление временной директории бэкапа '%s' завершилось неудачей."

#: backup_fs.py:471
#, python-format
msgid "Removing group '%s'..."
msgstr "Удаляем группу '%s'..."

#: backup_fs.py:486
#, python-format
msgid "Removing group '%s' failed."
msgstr "Удаление группы '%s' завершилось неудачей."

#: backup_fs.py:505
#, python-format
msgid "Can't read backup root directory '%s': %s."
msgstr "Ошибка при чтении корневой директории '%s': %s."

#: backup_fs.py:517
#, python-format
msgid "Bad group '%s' in backup root directory '%s'."
msgstr "Неверная группа '%s' в корневой директории бэкапа '%s'."

#: backup_fs.py:524
#, python-format
msgid "Gotten backup groups list: %s."
msgstr "Полученный список групп: %s."

#: backup_fs.py:530
msgid "Removing old groups..."
msgstr "Удаляем старые группы..."

#: backup_fs.py:539
msgid "Removing old groups failed."
msgstr "Удаление старых групп завершилось неудачей."

#: backup_fs.py:569
#, python-format
msgid "Can't write backup extern files info to '%s': %s."
msgstr "Ошибка при записи информации о внешних файлах в '%s': %s."

#: backup_fs.py:593
#, python-format
msgid "Can't write backup unique files info to '%s': %s."
msgstr "Ошибка при записи информации об уникальных файлах в '%s': %s."

#: backup_fs.py:612
#, python-format
msgid "Can't write backup log file '%s': %s."
msgstr "Ошибка при записи лога в '%s': %s."

#: config.py:91
msgid "Configuration file error:"
msgstr "Ошибка конфигурационного файла:"

#: config.py:99
msgid "Python module ConfigObj is not installed. Please install it."
msgstr ""
"Python'овский модуль ConfigObj не установлен. Пожалуйста, установите его."

#: config.py:111
#, python-format
msgid "Configuration file error: %s"
msgstr "Ошибка конфигурационного файла: %s"

#: config.py:145
#, python-format
msgid "%s '%s' value '%s' is not an absolute path."
msgstr "%s значение опции '%s' ('%s') - не абсолютный путь."

#: config.py:155
#, python-format
msgid "%s bad '%s' value '%s'. Allowed values: %s."
msgstr "%s неверное значение опции '%s': '%s'. Допустимые значения: %s."

#: config.py:166 config.py:170 config.py:183
#, python-format
msgid "%s bad '%s' value '%s'."
msgstr "%s неверное значение опции '%s': '%s'."

#: config.py:190
#, python-format
msgid "%s bad '%s' value: it can't be a multiline string."
msgstr "%s неверное значение опции '%s' - оно не может быть многострочным."

#: config.py:206
#, python-format
msgid "%s bad '%s' type."
msgstr "%s неверный тип опции '%s'."

#: config.py:215
#, python-format
msgid "%s backup entry path '%s' is not an absolute path."
msgstr "%s путь элемента бэкапа '%s' - не абсолютный путь."

#: config.py:232
#, python-format
msgid "%s bad '%s' value '%s' for backup entry '%s'. Allowed values: %s."
msgstr ""
"%s неверное значение опции '%s' ('%s') для элемента бэкапа '%s'. Допустимые "
"значения: %s. "

#: config.py:260
#, python-format
msgid "%s bad filter regex string for backup entry '%s': '%s'."
msgstr ""
"%s неверное регулярное выражение для фильтра элемента бэкапа '%s': '%s'."

#: config.py:267
#, python-format
msgid "%s bad filter string for backup entry '%s': '%s'."
msgstr "%s неверная строка фильтра для элемента бэкапа '%s': '%s'."

#: config.py:277
#, python-format
msgid "%s bad '%s' type for backup entry '%s'."
msgstr "%s неверный тип опции '%s' для элемента бэкапа '%s'."

#: config.py:282
#, python-format
msgid "%s unknown option '%s' in backup entry '%s'."
msgstr "%s неизвестная опция '%s' в элементе бэкапа '%s'."

#: config.py:289
#, python-format
msgid "%s unknown option '%s'."
msgstr "%s неизвестная опция '%s'."

#: config.py:292
#, python-format
msgid ""
"Backup config dump:\n"
"%s"
msgstr ""
"Дамп переменных конфига:\n"
"%s"

#: config.py:297
#, python-format
msgid "%s 'backup_root' option not found in config. It must exists."
msgstr ""
"%s опция 'backup_root' не найдена в конфигурационном файле, но это "
"обязательная опция."

#: config.py:301
#, python-format
msgid "%s no backup entries found in config. At least one must exists."
msgstr ""
"%s конфигурационный файл не содержит ни одного элемента бэкапа. Каждый "
"конфигурационный файл должен содержать хотя бы один элемент бэкапа."

#: config.py:308
#, python-format
msgid ""
"%s option 'send_email_report' set to true, but 'mail_to' option is not set."
msgstr ""
"%s опция 'send_email_report' установлена в true, но опция 'mail_to' не "
"установлена."

#: config.py:311
#, python-format
msgid ""
"%s option 'send_email_report' set to true, but 'mail_program' option is not "
"set."
msgstr ""
"%s опция 'send_email_report' установлена в true, но опция 'mail_program' не "
"установлена."

#: config.py:325
#, python-format
msgid "Can't get '%s' absolute path: %s."
msgstr "Не удалось получить абсолютный путь '%s': %s."

#: lib.py:211
#, python-format
msgid "E: Formatting log for output failed with Unicode conversion error: %s."
msgstr ""
"E: Форматирование лога для последующего вывода завершилось ошибкой "
"преобразования в Unicode: %s."

#: lib.py:279
#, python-format
msgid "Can't chmod '%s': %s."
msgstr "Не удалось изменить права доступа '%s': %s."

#: lib.py:294
#, python-format
msgid "Can't decompress file '%s' - it is not *.bz2 or *.gz file."
msgstr "Ошибка при распаковке файла '%s' - это не *.bz2 или *.gz файл."

#: lib.py:305
#, python-format
msgid "Error while reading compressed file '%s': %s."
msgstr "Ошибка при чтении запакованного файла '%s': %s."

#: lib.py:313
#, python-format
msgid "Can't create file '%s': %s."
msgstr "Ошибка при создании файла '%s': %s."

#: lib.py:326
#, python-format
msgid "Error while copying file '%s' to '%s'. '%s': %s."
msgstr "Ошибка при копировании файла '%s' в '%s'. '%s': %s."

#: lib.py:333
#, python-format
msgid "Can't close file '%s': %s."
msgstr "Не удалось закрыть файл '%s': %s."

#: lib.py:337
#, python-format
msgid "Decompressing of file '%s' failed."
msgstr "Распаковка сжатого файла '%s' завершилась неудачей."

#: lib.py:371
#, python-format
msgid "Can't stat '%s': %s."
msgstr "Ошибка при получении информации о файле '%s': %s."

#: lib.py:400
#, python-format
msgid "Can't create directory '%s': %s."
msgstr "Ошибка при создании директории '%s': %s."

#: lib.py:415
#, python-format
msgid "Can't create temp directory in '%s': %s."
msgstr "Ошибка при создании временной директории в '%s': %s."

#: lib.py:417
#, python-format
msgid "Can't create temp directory: %s."
msgstr "Ошибка при создании временной директории: %s."

#: lib.py:432
#, python-format
msgid "Can't create temp file in '%s': %s."
msgstr "Ошибка при создании временного файла в '%s': %s."

#: lib.py:434
#, python-format
msgid "Can't create temp file: %s."
msgstr "Ошибка при создании временного файла: %s."

#: lib.py:443
#, python-format
msgid "Can't move '%s' to '%s': %s."
msgstr "Не удалось переместить '%s' в '%s': %s."

#: lib.py:454
#, python-format
msgid "Can't rename '%s' to '%s': %s."
msgstr "Ошибка при переименовании '%s' в '%s': %s."

#: lib.py:469
#, python-format
msgid "Can't delete '%s': %s."
msgstr "Не удалось удалить '%s': %s."

#: lib.py:474 lib.py:486
#, python-format
msgid "Deleting of '%s' failed."
msgstr "Удаление '%s' завершилось неудачей."

#: lib.py:496
#, python-format
msgid "Running command '%s'..."
msgstr "Запускаем команду '%s'..."

#: lib.py:512
#, python-format
msgid "Can't create a pipe: %s."
msgstr "Ошибка при создании pipe: %s."

#: lib.py:528
#, python-format
msgid "Running command '%s' failed: %s."
msgstr "Запуск команды '%s' завершился ошибкой '%s'."

#: lib.py:539
#, python-format
msgid "Can't write data to process stdin: %s."
msgstr "Ошибка при записи данных в стандартный поток ввода процесса: %s."

#: lib.py:545
#, python-format
msgid "Can't close command '%s' stdin pipe descriptor: %s."
msgstr ""
"Ошибка при закрытии дескриптора стандартного потока ввода для команды '%s': %"
"s."

#: lib.py:546
msgid "Killing started command process..."
msgstr "Завершаем процесс запущенной команды..."

#: lib.py:571
#, python-format
msgid "Error! Can't get command '%s' output: %s."
msgstr "Ошибка! Не удалось получить вывод запущенной команды '%s': %s."

#: lib.py:574
#, python-format
msgid "Command '%s' exit status: %d."
msgstr "Статус завершения команды '%s': %d."

#: lib.py:577
#, python-format
msgid "Running command '%s' failed."
msgstr "Запуск команды '%s' завершился неудачей."

#: lib.py:590
#, python-format
msgid "Sending email message from '%s' to '%s' by email program '%s'..."
msgstr ""
"Отсылаем email сообщение от '%s' на '%s' при помощи email программы '%s'..."

#: lib.py:601
#, python-format
msgid "Can't create email message: %s"
msgstr "Ошибка при создании email сообщения: %s."

#: lib.py:607
#, python-format
msgid ""
"Sending email message failed. Email program return exit status %d. Shell "
"output:\n"
"%s"
msgstr ""
"Не удалось отослать email сообщение. Email программа возвратила статус "
"завершения %d. Вывод командной оболочки:\n"
"%s"

#: lib.py:610
msgid "Sending email message failed."
msgstr "Не удалось отослать email сообщение."

#: lib.py:613
msgid "Email message has been sent."
msgstr "Email сообщение было успешно отправлено."

#: lib.py:623
#, python-format
msgid "Can't delete file '%s': %s."
msgstr "Ошибка при удалении файла '%s': %s."

#: lib.py:635
#, python-format
msgid "Removing '%s' failed."
msgstr "Удаление '%s' завершилось неудачей."

#: main.py:46
msgid "Program has been interrupted by SIGINT."
msgstr "Программа была прервана сигналом SIGINT."

#: main.py:60
msgid ""
"${program_name} ${program_version}  Copyright (c) ${copyright_years} "
"Konishchev Dmitry\n"
"\n"
"Usage: ${program_command_name} [OPTIONS] [PATH]\n"
"\n"
"Options:\n"
"  -r, --restore    - restore mode\n"
"  -d, --debug      - show debug messages\n"
"  -h, --help       - show this help\n"
"  --version        - show program version\n"
"\n"
"Examples:\n"
"  # Create backup with default configuration file (${default_config})\n"
"  ${program_command_name}\n"
"\n"
"  # Create backup with configuration file example.cfg\n"
"  ${program_command_name} example.cfg\n"
"\n"
"  # Restore backup '~/backups/current/2008.08.04_23.31.47'\n"
"  # to ./2008.08.04_23.31.47\n"
"  ${program_command_name} -r ~/backups/current/2008.08.04_23.31.47\n"
"\n"
"Files:\n"
"  ${default_config} - default configuration file."
msgstr ""
"${program_name} ${program_version}  Copyright (c) ${copyright_years} Конищев "
"Дмитрий\n"
"\n"
"Использование: ${program_command_name} [OPTIONS] [PATH]\n"
"\n"
"Опции:\n"
"  -r, --restore    - режим восстановления\n"
"  -d, --debug      - отображать отладочные сообщения\n"
"  -h, --help       - вывести данное сообщение\n"
"  --version        - вывести версию программы\n"
"\n"
"Примеры:\n"
"  # Создает бэкап, используя конфигурационный файл по умолчанию "
"(${default_config})\n"
"  ${program_command_name}\n"
"\n"
"  # Создает бэкап с конфигурационным файлом example.cfg\n"
"  ${program_command_name} example.cfg\n"
"\n"
"  # Восстанавливает бэкап '~/backups/current/2008.08.04_23.31.47'\n"
"  # в ./2008.08.04_23.31.47\n"
"  ${program_command_name} -r ~/backups/current/2008.08.04_23.31.47\n"
"\n"
"Файлы:\n"
"  ${default_config} - конфигурационный файл по умолчанию."

#: main.py:124
msgid "Starting backup mode..."
msgstr "Запускаем режим бэкапа..."

#: main.py:131
#, python-format
msgid "Backup with configuration file '%s' failed."
msgstr "Бэкап с конфигурационным файлом '%s' завершился неудачей."

#: main.py:134
msgid "Starting restore mode..."
msgstr "Запускаем режим восстановления..."

#: main.py:141 restore.py:124
#, python-format
msgid "Restoring of '%s' failed."
msgstr "Восстановление '%s' завершилось неудачей."

#: main.py:167
#, python-format
msgid "Usage: %s -h"
msgstr "Использование: %s -h"

#: main.py:172
#, python-format
msgid "%s %s"
msgstr "%s %s"

#: restore.py:59
msgid "Deleting temporary files..."
msgstr "Удаляем временные файлы..."

#: restore.py:76
msgid "Restoring of backup extern files will be impossible."
msgstr "Восстановление внешних файлов бэкапа будет невозможно."

#: restore.py:83
#, python-format
msgid ""
"Opening archive with backup data for restoring backup '%s' in group '%s' "
"failed."
msgstr ""
"Открытие архива с данными восстанавливаемого бэкапа '%s' в группе '%s' "
"завершилось ошибкой."

#: restore.py:95
#, python-format
msgid "Restoring of file '%s' failed."
msgstr "Восстановление файла '%s' завершилось неудачей."

#: restore.py:102
#, python-format
msgid "File '%s' is marked as extern. Skipping restoring of it..."
msgstr "Файл '%s' помечен как внешний. Пропускаем его восстановление..."

#: restore.py:108
#, python-format
msgid ""
"Backup is broken: file '%s' is link to extern file, but extern files list "
"has not info about it. Skipping restoring of it."
msgstr ""
"Бэкап поврежден: файл '%s' - ссылка на внешний файл, но список внешних "
"файлов не содержит информации о нем. Пропускаем данный файл."

#: restore.py:114
#, python-format
msgid "Can't find extern file for '%s'. Skipping restoring of it."
msgstr ""
"Ошибка! Не удалось найти внешний файл для файла '%s'. Пропускаем данный файл."

#: restore.py:135
#, python-format
msgid "Adding extern file '%s' for '%s' from backup '%s' to temp storage..."
msgstr ""
"Добавляем внешний файл '%s' для '%s' из бэкапа '%s' во временный архив..."

#: restore.py:148
#, python-format
msgid "Opening archive with backup data for backup '%s' in group '%s' failed."
msgstr "Не удалось открыть архив с данными бэкапа '%s' группы '%s'."

#: restore.py:151
#, python-format
msgid ""
"Extern file '%s' for '%s' is located in unavailable archive for backup '%s'."
msgstr ""
"Внешний файл '%s' для '%s' находится в недоступном архиве для бэкапа '%s'."

#: restore.py:158
#, python-format
msgid ""
"Backup '%s' is broken: it has file '%s', but this file is not exists in "
"backup data archive."
msgstr ""
"Бэкап '%s' поврежден: он имеет файл '%s', но архив с данными бэкапа не "
"содержит этот файл."

#: restore.py:164
#, python-format
msgid ""
"File '%s' is link to extern file '%s' in backup '%s' which is not a regular "
"file."
msgstr ""
"Файл '%s' - ссылка на внешний файл '%s' бэкапа '%s', который не является "
"обычным файлом."

#: restore.py:176
#, python-format
msgid "Restoring '%s' from extern file failed."
msgstr "Восстановление '%s' из внешнего файла завершилось ошибкой."

#: restore.py:185
#, python-format
msgid "Restoring '%s' to '%s'..."
msgstr "Восстанавливаем '%s' в '%s'..."

#: restore.py:195
msgid "Creating temp tar storage failed."
msgstr "Создание временного архива завершилось ошибкой."

#: restore.py:199
msgid "Adding all needed files to temp storage..."
msgstr "Добавляем все необходимые файлы во временный архив..."

#: restore.py:205
#, python-format
msgid "Extracting files from temp storage to '%s'..."
msgstr "Распаковываем все файлы из временного архива в '%s'..."

#: restore.py:216
msgid "Restoring completed with errors."
msgstr "Восстановление завершилось с ошибками."

#: restore.py:218
msgid "Restoring completed with warnings."
msgstr "Восстановление завершилось с некритическими ошибками."

#: restore.py:220
msgid "Restoring successfully completed."
msgstr "Восстановление успешно завершено."

#: storage.py:58
#, python-format
msgid "Can't add '%s' to tar file '%s': %s."
msgstr "Ошибка при добавлении '%s' в tar файл '%s': %s."

#: storage.py:69
#, python-format
msgid "Can't add file to tar file '%s': %s."
msgstr "Ошибка при добавлении файла в tar файл '%s': %s."

#: storage.py:86
#, python-format
msgid "File type of '%s' is not supported."
msgstr "Тип файла '%s' не поддерживается."

#: storage.py:100
#, python-format
msgid "Can't close tar file '%s': %s."
msgstr "Ошибка при закрытии tar файла '%s': %s."

#: storage.py:119
#, python-format
msgid "Creating tar file '%s' members cache..."
msgstr "Создаем кэш с объектами tar файла '%s'..."

#: storage.py:132
msgid "Members cache has been created."
msgstr "Кэш с объектами tar файла создан."

#: storage.py:140
#, python-format
msgid "Can't extract files from tar file '%s' to '%s': %s."
msgstr "Ошибка при распаковке файлов из tar архива '%s' в '%s': %s."

#: storage.py:151 storage.py:199
#, python-format
msgid "Can't get file '%s' info: %s."
msgstr "Не удалось получить информацию о файле '%s': %s."

#: storage.py:187
#, python-format
msgid "Getting tar file '%s' members list..."
msgstr "Получаем список объектов tar файла '%s'..."

#: storage.py:189
msgid "Members list has been gotten."
msgstr "Список объектов tar файла получен."

#: storage.py:218
#, python-format
msgid "Opening tar file '%s' with mode '%s'..."
msgstr "Открываем tar файл '%s' в режиме '%s'..."

#: storage.py:223
#, python-format
msgid "Can't open tar file '%s': %s."
msgstr "Ошибка при открытии tar файла '%s': %s."

#: storage.py:226
msgid "Tar file has been opened."
msgstr "Tar файл был успешно открыт."

#: storage.py:266
#, python-format
msgid "Finding archive with backup data in '%s'..."
msgstr "Поиск архива с данными бэкапа в '%s'..."

#: storage.py:277
#, python-format
msgid "Opening backup '%s' data archive failed."
msgstr "Не удалось открыть архив бэкапа '%s'."

#: storage.py:281
#, python-format
msgid "Can't find archive with backup data in '%s'."
msgstr "Не удалось найти архив с данными бэкапа в '%s'."

#: storage.py:284
#, python-format
msgid "Archive found: '%s'."
msgstr "Архив найден: '%s'."

#: storage.py:289
#, python-format
msgid "Archive type: %s."
msgstr "Тип архива: %s."

#: storage.py:298
msgid "Creating tar storage temp directory failed."
msgstr "Создание временной директории для tar архива завершилось неудачей."

#: storage.py:352
#, python-format
msgid "Can't extract tar archive '%s' to '%s': %s."
msgstr "Ошибка при распаковке tar архива '%s' в '%s': %s."

#: storage.py:358
msgid "Compressing backup data archive..."
msgstr "Сжимаем архив с данными бэкапа..."

#: storage.py:365
#, python-format
msgid "Creating archive '%s' with backup data failed."
msgstr "Создание архива с данными бэкапа '%s' завершилось неудачей."

#: storage.py:368
msgid "Tar archive will be used instead of 7z archive."
msgstr "Вместо 7z архива будет использован tar архив."

#: storage.py:379
#, python-format
msgid "Uncompressing 7z archive '%s'..."
msgstr "Распаковываем 7z архив '%s'..."

#: storage.py:385
#, python-format
msgid ""
"Uncompressing 7z archive with backup data '%s' to '%s' failed. Shell "
"output:\n"
"%s"
msgstr ""
"Распаковка 7z архива с данными бэкапа '%s' в '%s' завершилось неудачей. "
"Вывод командной оболочки:\n"
"%s"

#: storage.py:388
#, python-format
msgid "Uncompressing 7z archive with backup data '%s' failed."
msgstr "Распаковка 7z архива с данными бэкапа '%s' завершилась неудачей."

#: storage.py:391
msgid "Uncompressing 7z archive has been finished successfully."
msgstr "Распаковка 7z архива успешно завершена."

#: storage.py:400
#, python-format
msgid "Decompressing archive with backup data '%s' to '%s' failed."
msgstr "Распаковка архива с данными бэкапа '%s' в '%s' завершилась неудачей."

#: storage.py:412
#, python-format
msgid "Compressing tar archive '%s' to 7z..."
msgstr "Сжимаем tar архив '%s' в 7z архив..."

#: storage.py:418
#, python-format
msgid ""
"Compressing archive with backup data '%s' to 7z failed. Shell output:\n"
"%s"
msgstr ""
"Сжатие архива с данными бэкапа '%s' в 7z архив завершилось неудачей. Вывод "
"командной оболочки:\n"
"%s"

#: storage.py:421
#, python-format
msgid "Compressing archive with backup data '%s' to 7z failed."
msgstr "Сжатие архива с данными бэкапа '%s' в 7z архив завершилось неудачей."

#: storage.py:424
msgid "Compressing archive to 7z has been finished successfully."
msgstr "Сжатие архива с данными бэкапа '%s' в 7z архив успешно завершено."

#: storage.py:447
#, python-format
msgid "Uncompressing archive with backup data '%s'..."
msgstr "Распаковываем сжатый архив с данными бэкапа '%s'..."

#: storage.py:462
msgid "Uncompressing archive finished."
msgstr "Распаковка сжатого архива успешно завершена."

#: storage.py:500
#, python-format
msgid "Can't create tar file '%s': %s."
msgstr "Ошибка при создании tar файла '%s': %s."
